### ISSUE TITLE
按照您的方法设置了下，结果还是卡死

### ISSUE THREAD

**Issue by jami1024** [YeYinhai/el-tab-pane-ext#1]
# 版本
element-ui@2.13.0
# 代码

`html
<el-dialog title="申请服务器" :close-on-click-modal="false" :visible.sync="isFormVisible">
      <el-tabs v-model="activeName" type="border-card">
        <el-tab-pane-ext label="腾讯云" name="first">
          <template v-slot:content>
            <h1>ssss</h1>
          </template>
        </el-tab-pane-ext>
        <el-tab-pane-ext label="阿里云" name="second">
        </el-tab-pane-ext>
        <el-tab-pane-ext label="Ucloud云" name="third">
        </el-tab-pane-ext>
        <el-tab-pane-ext label="Aws云" name="fourth">
        </el-tab-pane-ext>
      </el-tabs>
      
      <div slot="footer" class="dialog-footer">
        <el-button @click="isFormVisible = false">取 消</el-button>
        <el-button type="primary" @click="add" >确 定</el-button>
      </div>
    </el-dialog>
`

**Comment by YeYinhai** [comment]
1.支持以上版本
vue@2.6.0
element-ui@2.13.0

2.使用el-tab-pane-ext的vue页，运行时内部不能有错误。(F12 可查看 console 是否有提示。)（以及一些属性的类型问题）
3.热编译也可能引起卡死。(具体原因同第二条)。

你根据上面几点排查下看看。

**Comment by jami1024** [comment]
我知道了、我vue版本是3.0了，我降element-ui的版本了，谢谢大佬。
